### ISSUE TITLE
Need to update dialoguer to 0.8.0

### ISSUE THREAD

**Issue by cflanny** [dangreco/gnome-egpu#5]
Some inherited dependency for 'dialoguer' is broken, which is fixed in dialoguer 0.8.0.  I made a branch and updated it on my laptop, but I can't push it to this repo because it's locked down, or I would have just put in a pull request.

For anyone else that has this issue, do the following:
1. clone the repo
2. in the Cargo.toml file, change the version of dialoguer to 0.8.0
3. run 'cargo build'
4. you'll find your new gnome-egpu binary in target/debug/gnome-egpu - move it somewhere useful (such as /usr/local/bin)

Cheers.

**Comment by zacharyburnett** [comment]
I also had this problem, and following these steps allowed me to build.

is `gnome-egpu.d` important?
